server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service-public
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service-public
          uri: lb://user-service
          predicates:
            - Path=/api/users/login,/api/users/register
        - id: user-service-protected
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: file-service-protected
          uri: lb://file-service
          predicates:
            - Path=/api/files/**
        - id: repository-service-protected
          uri: lb://repository-service
          predicates:
            - Path=/api/repositories/**,/api/comments/**
        - id: user-service-docs
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs/**
        - id: file-service-docs
          uri: lb://file-service
          predicates:
            - Path=/file-service/v3/api-docs/**
        - id: repository-service-docs
          uri: lb://repository-service
          predicates:
            - Path=/repository-service/v3/api-docs/**
        - id: swagger-ui
          uri: lb://api-gateway
          predicates:
            - Path=/swagger-ui/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: localhost

jwt:
  secret: thisissecretkeyforfilerepositoryprojectmicroserviceswithjwt
  expiration: 86400000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.filerepository: DEBUG
    org.springframework.web.reactive: DEBUG
