server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

jwt:
  secret: thisissecretkeyforfilerepositoryprojectmicroserviceswithjwt
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    com.filerepository: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /user-service/v3/api-docs
      - name: File Service
        url: /file-service/v3/api-docs
      - name: Repository Service
        url: /repository-service/v3/api-docs